### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by whb1993** [wanglu58/webssh#4]
环境 win10
python 3.7
运行后点击登录 报错，是否是因为版本原因？
![image](https://user-images.githubusercontent.com/22782738/97947237-a3477a00-1dc7-11eb-895b-bd4457ed375e.png)
![image](https://user-images.githubusercontent.com/22782738/97947299-d2f68200-1dc7-11eb-89ba-5bbe0bd3ccb4.png)

` return await application(scope, receive, send)
  File "C:\Users\97281\AppData\Local\Programs\Python\Python37\lib\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\97281\AppData\Local\Programs\Python\Python37\lib\site-packages\channels\sessions.py", line 172, in __call__
    return await self.inner(self.scope, receive, self.send)
  File "C:\Users\97281\AppData\Local\Programs\Python\Python37\lib\site-packages\channels\auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\97281\AppData\Local\Programs\Python\Python37\lib\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\97281\AppData\Local\Programs\Python\Python37\lib\site-packages\channels\routing.py", line 160, in __call__
    send,
  File "C:\Users\97281\AppData\Local\Programs\Python\Python37\lib\site-packages\asgiref\compatibility.py", line 33, in new_application
    instance = application(scope)
  File "C:\Users\97281\AppData\Local\Programs\Python\Python37\lib\site-packages\channels\generic\websocket.py", line 23, in __init__
    super().__init__(*args, **kwargs)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)
WebSocket DISCONNECT /webssh/ [127.0.0.1:11349]
HTTP GET /static/bootstrap/3.3.7/bootstrap.min.css.map 404 [0.07, 127.0.0.1:11344]
HTTP GET /static/xterm/3.14.5/xterm.min.css.map 404 [0.10, 127.0.0.1:11343]
HTTP GET / 200 [0.01, 127.0.0.1:11418]
HTTP GET /static/xterm/3.14.5/xterm.min.css.map 404 [0.03, 127.0.0.1:11418]
HTTP GET /static/bootstrap/3.3.7/bootstrap.min.css.map 404 [0.06, 127.0.0.1:11419]
HTTP GET /static/favicon.ico 200 [0.10, 127.0.0.1:11420]
WebSocket HANDSHAKING /webssh/ [127.0.0.1:11763]
Exception inside application: object.__init__() takes exactly one argument (the instance to initialize)
Traceback (most recent call last):
  File "C:\Users\97281\AppData\Local\Programs\Python\Python37\lib\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\97281\AppData\Local\Programs\Python\Python37\lib\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\97281\AppData\Local\Programs\Python\Python37\lib\site-packages\channels\sessions.py", line 172, in __call__
    return await self.inner(self.scope, receive, self.send)
  File "C:\Users\97281\AppData\Local\Programs\Python\Python37\lib\site-packages\channels\auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\97281\AppData\Local\Programs\Python\Python37\lib\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\97281\AppData\Local\Programs\Python\Python37\lib\site-packages\channels\routing.py", line 160, in __call__
    send,
  File "C:\Users\97281\AppData\Local\Programs\Python\Python37\lib\site-packages\asgiref\compatibility.py", line 33, in new_application
    instance = application(scope)
  File "C:\Users\97281\AppData\Local\Programs\Python\Python37\lib\site-packages\channels\generic\websocket.py", line 23, in __init__
    super().__init__(*args, **kwargs)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)
WebSocket DISCONNECT /webssh/ [127.0.0.1:11763]
`

**Comment by wanglu58** [comment]
有可能是你主机的密码输错了。
